#!/bin/bash

### BEGIN INIT INFO
# Provides:          [ service name ]
# Required-Start:    [ required boot facilities, see other init scripts for examples ]
# Required-Stop:     [ required boot facilities ]
# Should-Start:      [ requested, but not critical boot facilities ]
# Should-Stop:       [ requested, but not critical boot facilities ]
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: [ short description of service functionality ]
### END INIT INFO

# Enter the command you wish to run in between the parentheses, exactly as you
# would enter the command in your shell.
cmd=( sleep 120 )

# Set this to 1 if what you are executing will immediately fork. In this case,
# we don't attempt to write a pid (since it won't be valid) among other things.
# Ideally, don't fork, and reap the benefits. We'll background it ourselves.
will_fork_itself=0

# If what you want to kill looks different from what you're launching, enter a
# regex matching the process to kill here. This only matters if you have
# will_fork_itself on, or we can't find the PID file when we expect it.
override_kill_regex=''


# Ideally, don't edit anything from this point onwards.


script_name="${0##*/}"
cmd_name="${cmd[0]}"
pid_file="/var/run/${script_name}.pid"
time_file="/var/run/${script_name}.time"
force_will_fork_itself_mode=0

if [[ "$override_kill_regex" ]]; then
    regex="$override_kill_regex"
else
    # This could be too big of a net. Also it might be interpreted
    # wrongly cast as a regex. Hooray!
    regex="$cmd_name"
fi

pids=( $(pgrep -f "$regex") )
num_pids="${#pids[@]}"

running() {
    (( num_pids ))
}

pid_start_time() {
    local pid="$1"
    awk '{ print $22 }' "/proc/$pid/stat" 2>/dev/null
}

start_time_same() {
    local pid="$1"
    local our_time
    local their_time
    local i

    read our_time < "$time_file"
    their_time="$(pid_start_time "$pid")"

    (( our_time == their_time ))
}

case "$1" in
    start)
        printf 'Starting %s... ' "$cmd_name"

        if { read pid < "$pid_file" ; } >/dev/null 2>&1; then
            if kill -0 "$pid" >/dev/null 2>&1; then
                printf 'already running on PID %d\n' "$pid"
                exit 2
            fi
        fi

        if (( will_fork_itself )); then
            if "${cmd[@]}"; then
                echo ok
            else
                echo failed
            fi
        else
            if "${cmd[@]}" & then
                if ! { echo "$!" > "$pid_file" ; } >/dev/null 2>&1; then
                    printf 'failed to write PID file: %s\n' "$pid_file"
                    exit 3
                fi
                if ! pid_start_time "$!" > "$time_file" 2>/dev/null; then
                    printf 'failed to write time file: %s\n' "$time_file"
                    exit 4
                fi
                echo ok
            else
                echo failed
            fi
        fi
    ;;
    stop)
        printf 'Stopping %s... ' "$cmd_name"

        if ! (( will_fork_itself )); then
            if ! { read pid < "$pid_file" ; } >/dev/null 2>&1; then
                printf 'PID file unreadable, falling back to pkill: %s\n' "$pid_file"
                force_will_fork_itself_mode=1
            else
                if start_time_same "$pid"; then
                    if kill "$pid" >/dev/null 2>&1; then
                        echo ok
                    else
                        echo "not running"
                    fi
                elif kill -0 "$pid" >/dev/null 2>&1; then
                    printf 'We did not start the process with PID %d, aborting\n' "$pid"
                    exit 4
                else
                    echo "not running"
                fi
            fi
        fi

        if (( will_fork_itself )) || (( force_will_fork_itself_mode )); then
            if running; then
                pkill -f "$regex"
                printf '%d processes running and signalled, PIDs: %s\n' "$num_pids" "${pids[*]}"
            else
                echo "already stopped"
            fi
        fi
    ;;
    restart)
        "$0" stop
        "$0" start
    ;;
    status)
        if ! (( will_fork_itself )); then
            if { read pid < "$pid_file" ; } >/dev/null 2>&1; then
                if start_time_same "$pid"; then
                    printf 'Running, PID: %d\n' "$pid"
                elif kill -0 "$pid" >/dev/null 2>&1; then
                    printf 'A process with PID %d exists, but does not appear to be the one we want\n' "$pid"
                else
                    printf 'Stopped, but pid file still exists: %s\n' "$pid_file"
                fi
            else
                echo stopped
            fi
        else
            if running; then
                printf '%d instances are running. PIDs: %s\n' "$num_pids" "${pids[*]}"
            else
                echo "not running"
            fi
        fi
    ;;
    *)
        printf 'Usage: %s {status|start|stop|restart}\n' "$0"
        exit 1
    ;;
esac
